language: generic
# Tell Travis we need super level permission for docker.
sudo: required
# Tell Travis to install docker.
services:
  - docker

before_install:
  - docker build -t obionestar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true obionestar/docker-react npm run test
